version: '3.8'

services:
    nginx:
        user: "root"
        container_name: job-talks-nginx
        image: nginx:stable-alpine
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/html
        depends_on:
            - php
        networks:
            - internal
        healthcheck:
            test: ["CMD", "nginx", "-t"]
            interval: 30s
            retries: 3

    php:
        user: "root"
        container_name: job-talks-php
        working_dir: /var/www/html
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        env_file:
            - .env
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_HOST=db
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - internal
        healthcheck:
            test: ["CMD", "php-fpm", "-t"]
            interval: 30s
            retries: 3

    db:
        user: "root"
        container_name: job-talks-db
        image: mariadb:latest
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3308:3306"
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            retries: 3
        networks:
            - internal

volumes:
    dbdata:
        driver: local

networks:
    internal:
        driver: bridge
